### ISSUE TITLE
Start with location information

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/open311-nodejs#23]
The request process should probably start with asking for the location information.

We are receiving a percentage of tickets these days where users are putting the location and contact information into the details field.  Then, later on, on the location screen, they just skip over that; because they feel they've already provided that information in the details field.

The problem with this is that the details field is publically available information.  We do not want people putting their address and phone numbers into that field.  We want them to put them into the appropriate fields, so we can hide that information when we publish the ticket reports.

**Comment by inghamn** [comment]
#33

**Comment by adabutch** [comment]
Via Linda today: 

add default to 401 morton

**Comment by adabutch** [comment]
Rather interesting note,

https://github.com/City-of-Bloomington/open311-nodejs/releases/tag/1.1.0

Notice the page reorder, Lucy, among others pushed for the location & personal info last.

**Comment by adabutch** [comment]
Page Order via v2:

`Cat` / `Sec. Cat` / `Location` / `Info` / `Questions` + **`submit`**

- - - 

Check entires in ~6mo. for `before vs after` descriptions.
