### ISSUE TITLE
master address API

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/open311-nodejs#29]
update to use the new API, see below

**Comment by inghamn** [comment]
The new Master Address route for searching addresses is:

https://bloomington.in.gov/master_address/addresses

The search query gets passed as the "address" parameter.  As usual pass a "format" parameter to get JSON out.

https://bloomington.in.gov/master_address/addresses?address=401+N+Morton;format=json

**Comment by adabutch** [comment]
@sethCOB - notice https://github.com/City-of-Bloomington/open311-nodejs/commit/e71c7e9602d59489af424f1e0ba223db460a7a3f#r34271546
