### ISSUE TITLE
Show users a notice that their name will be public record

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/open311-nodejs#30]
Inform users that the information they provide is public record. 

Potentially present in the same fashion as the non-emergency modal.

Open to ideas/discussion.

cc // @rbdietz

**Comment by inghamn** [comment]
This has a direct impact on what we decide to publish in uReport.

https://github.com/City-of-Bloomington/uReport/issues/363

**Comment by inghamn** [comment]
#33

**Comment by adabutch** [comment]
![pub-record-notice](https://user-images.githubusercontent.com/2372040/71225277-07dc1200-22a6-11ea-8854-c36c4ca82e85.gif)

**Comment by adabutch** [comment]
![pub-record-notice](https://user-images.githubusercontent.com/2372040/71256550-0e4aa800-22ff-11ea-855e-af38f60b9b8e.gif)

**Comment by adabutch** [comment]
> **The information you provide is retained as public record**

**Comment by rbdietz** [comment]
Can we make this a single click through, I don't think we need two steps.

Here is text that Legal has vetted...

Information you provide through uReport is stored and retained by the City
as a public record.




Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0076 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
@rbdietz update below

![Screen Shot 2019-12-20 at 11 44 14 AM](https://user-images.githubusercontent.com/2372040/71269795-27168600-231e-11ea-88ff-77548dbc8dbd.png)

via 6ea85631ead53eedd5f1d5d8cdd9980892287516
