### ISSUE TITLE
periodic submission freeze

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/open311-nodejs#40]
Note: canvas behaving as expected

**Comment by adabutch** [comment]
Or perhaps better, auto-magically downgrade the img quality if too big.

**Comment by adabutch** [comment]
https://bloomington.in.gov/crm/tickets/view?ticket_id=171426

**Comment by adabutch** [comment]
np at 15mb on desktop

**Comment by inghamn** [comment]
The server (Apache + PHP) has a max POST size of 10MB.  Now, there's probably some compression going on during the POST and all, but once you start going over that size, the request is going to hang.  There is no error response.  Once you hit that size, Apache just stops listening to you and forgets about whatever request you started.

**Comment by adabutch** [comment]
note: CRM stack max post limit 10mb
