### ISSUE TITLE
build app

### ISSUE THREAD

**Issue by slamonega** [City-of-Bloomington/open311-nodejs#59]
I tried in a fresh ubuntu 18.04 (digitalocean) with just and only install of node and npm, followed instructions, and could not build the app.
What is the simplest way of it?

**Comment by adabutch** [comment]
@slamonega ~

This is a front-end client app for our [uReport](https://github.com/City-of-Bloomington/uReport) CRM  [Open311](https://www.open311.org/) app. You'll need an equivalent API serving the endpoints this client app expects to consume. You'll also need an .env mapped to the secrets. Lastly, at minimum, you'll need to customize the hompage icons to whatever categories you choose when running your API and get an API key with Google for reCaptcha.

I hope this helps, thanks!

**Comment by slamonega** [comment]
Hello Adam, could you share some "an .env mapped to the secrets" as example, my IT skills are not extensive, I will try to build the app and after customize the other things. My email is slamonega@gmail.com if you whant to contact directly.

**Comment by adabutch** [comment]
@slamonega - just emailed you with an example env.
