### ISSUE TITLE
Allow for submitting without a location

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/open311-nodejs#64]
It would be nice if users could clear the location and submit without a specific place.  Not all the reported problems are at a place.  Also, there are a few categories, like "Website feedback" where a location doesn't make sense.

**Comment by adabutch** [comment]
@inghamn - I'm with you on this, just want to point out the API spec for consideration.

Do you feel, in this case, passing on an empty string is sufficient to conform to the requirement?

http://wiki.open311.org/GeoReport_v2/


> location parameter | A full location parameter must be submitted. | One of lat & long or address_string or address_id

**Comment by inghamn** [comment]
I'd want to ignore the API spec in this case.  I'm working through so many data integrity problems related to the lat, long or address that came in not relating to the actual ticket.

For me, it would make sense to have the user make proactive, positive action to supply a location.
